# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

executors:
  gp-machine:
    machine: true

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-base-monorepo:
    executor: gp-machine
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Docker build
          command: docker build . -t greenpress/monorepo:$CIRCLE_BRANCH
      - run: docker push greenpress/monorepo:$CIRCLE_BRANCH
  build-apps:
    executor: gp-machine
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    parallelism: 4
    steps:
      - run: |
          cd compose/builders
          docker build . -f admin.Dockerfile -t greenpress/admin-panel:$CIRCLE_BRANCH
          docker push greenpress/admin-panel:$CIRCLE_BRANCH
      - run: |
          cd compose/builders
          docker build . -f auth.Dockerfile -t greenpress/auth:$CIRCLE_BRANCH
          docker push greenpress/auth:$CIRCLE_BRANCH
      - run: |
          cd compose/builders
          docker build . -f assets.Dockerfile -t greenpress/assets:$CIRCLE_BRANCH
          docker push greenpress/assets:$CIRCLE_BRANCH
      - run: |
          cd compose/builders
          docker build . -f blog-front.Dockerfile -t greenpress/blog-front:$CIRCLE_BRANCH
          docker push greenpress/blog-front:$CIRCLE_BRANCH
workflows:
  build-monorepo:
    jobs:
      -  build-base-monorepo:
           filters:
             branches:
               only: main
      -  build-apps:
           requires:
             - build-base-monorepo
           filters:
             branches:
               only: main
